flowchart TD
  UserRequest["User request"]
  Decision{Record exists?}
  agentation_baseline_spec_7c288669["agentation-baseline.spec"]
  UserRequest --> agentation_baseline_spec_7c288669
  agentation_baseline_spec_7c288669 --> agentation_baseline_spec_7c288669_result["result"]
  useUpdater_db2b740b["useUpdater"]
  UserRequest --> useUpdater_db2b740b
  useUpdater_db2b740b --> useUpdater_db2b740b_write["write/update"]
  useUpdater_db2b740b_write --> useUpdater_db2b740b_result["result"]
  useTraceCollector_e3f811c3["useTraceCollector"]
  UserRequest --> useTraceCollector_e3f811c3
  useTraceCollector_e3f811c3 --> useTraceCollector_e3f811c3_result["result"]
  useTraceCollector_e3f811c3 --> otelReceiver_bd752dec
  useTraceCollector_e3f811c3 --> traceConfig_7e9b1320
  useTraceCollector_e3f811c3 --> sessionLinking_8e056ceb
  useTestImport_136ded43["useTestImport"]
  UserRequest --> useTestImport_136ded43
  useTestImport_136ded43 --> useTestImport_136ded43_result["result"]
  useTestImport_136ded43 --> junit_018bb207
  useTestImport_136ded43 --> testRuns_ebc7ce74
  useSnapshots_2b09c48f["useSnapshots"]
  UserRequest --> useSnapshots_2b09c48f
  useSnapshots_2b09c48f --> useSnapshots_2b09c48f_result["result"]
  useSnapshots_2b09c48f --> snapshots_2b36a6e6
  useSessionImport_69292424["useSessionImport"]
  UserRequest --> useSessionImport_69292424
  useSessionImport_69292424 --> useSessionImport_69292424_result["result"]
  useSessionImport_69292424 --> agentTrace_bc847946
  useSessionImport_69292424 --> sessionLinking_8e056ceb
  useSessionImport_69292424 --> sessionBadges_4a38460b
  useSessionImport_69292424 --> kimiAdapter_baf31ed8
  useSessionImport_69292424 --> story_anchors_api_279f63a1
  useRepoLoader_df6f8864["useRepoLoader"]
  UserRequest --> useRepoLoader_df6f8864
  useRepoLoader_df6f8864 --> useRepoLoader_df6f8864_result["result"]
  useRepoLoader_df6f8864 --> codexConfig_229b7351
  useRepoLoader_df6f8864 --> indexer_70fa78e5
  useRepoLoader_df6f8864 --> otelReceiver_bd752dec
  useCommitData_29c16895["useCommitData"]
  UserRequest --> useCommitData_29c16895
  useCommitData_29c16895 --> useCommitData_29c16895_result["result"]
  useCommitData_29c16895 --> agentTrace_bc847946
  useCommitData_29c16895 --> git_9a881b9b
  useCommitData_29c16895 --> indexer_70fa78e5
  useAutoIngest_56f90d17["useAutoIngest"]
  UserRequest --> useAutoIngest_56f90d17
  useAutoIngest_56f90d17 --> useAutoIngest_56f90d17_result["result"]
  useAutoIngest_56f90d17 --> sessionBadges_4a38460b
  useAutoIngest_56f90d17 --> otelReceiver_bd752dec
  story_anchors_api_279f63a1["story-anchors-api"]
  UserRequest --> story_anchors_api_279f63a1
  story_anchors_api_279f63a1 --> story_anchors_api_279f63a1_result["result"]
  atlas_api_0fe43c81["atlas-api"]
  UserRequest --> atlas_api_0fe43c81
  atlas_api_0fe43c81 --> atlas_api_0fe43c81_result["result"]
  generate_dataset_d06adda7["generate-dataset"]
  UserRequest --> generate_dataset_d06adda7
  generate_dataset_d06adda7 --> generate_dataset_d06adda7_result["result"]
  useDashboardViewState_0962a456["useDashboardViewState"]
  UserRequest --> useDashboardViewState_0962a456
  useDashboardViewState_0962a456 --> useDashboardViewState_0962a456_result["result"]
  useDashboardViewState_0962a456 --> narrativeTelemetry_70dfa1c5
  narrativeSurfaceData_d4f28a0b["narrativeSurfaceData"]
  UserRequest --> narrativeSurfaceData_d4f28a0b
  narrativeSurfaceData_d4f28a0b --> narrativeSurfaceData_d4f28a0b_result["result"]
  docsAutoLoad_44c379b9["docsAutoLoad"]
  UserRequest --> docsAutoLoad_44c379b9
  docsAutoLoad_44c379b9 --> docsAutoLoad_44c379b9_result["result"]
  branchHeaderMapper_4dd9295b["branchHeaderMapper"]
  UserRequest --> branchHeaderMapper_4dd9295b
  branchHeaderMapper_4dd9295b --> branchHeaderMapper_4dd9295b_result["result"]
  useTraceCollector_test_1261d5ea["useTraceCollector.test"]
  UserRequest --> useTraceCollector_test_1261d5ea
  useTraceCollector_test_1261d5ea --> useTraceCollector_test_1261d5ea_result["result"]
  useTraceCollector_test_1261d5ea --> useTraceCollector_e3f811c3
  useTestImport_test_da639ade["useTestImport.test"]
  UserRequest --> useTestImport_test_da639ade
  useTestImport_test_da639ade --> useTestImport_test_da639ade_result["result"]
  useTestImport_test_da639ade --> useTestImport_136ded43
  useRepoLoader_test_c0765b39["useRepoLoader.test"]
  UserRequest --> useRepoLoader_test_c0765b39
  useRepoLoader_test_c0765b39 --> useRepoLoader_test_c0765b39_result["result"]
  useRepoLoader_test_c0765b39 --> useRepoLoader_df6f8864
  useRepoFileExistence_test_ae1ae469["useRepoFileExistence.test"]
  UserRequest --> useRepoFileExistence_test_ae1ae469
  useRepoFileExistence_test_ae1ae469 --> useRepoFileExistence_test_ae1ae469_result["result"]
  useAutoIngest_test_c64ef81e["useAutoIngest.test"]
  UserRequest --> useAutoIngest_test_c64ef81e
  useAutoIngest_test_c64ef81e --> useAutoIngest_test_c64ef81e_result["result"]
  useAutoIngest_test_c64ef81e --> useAutoIngest_56f90d17
  narrativeTelemetry_70dfa1c5["narrativeTelemetry"]
  UserRequest --> narrativeTelemetry_70dfa1c5
  narrativeTelemetry_70dfa1c5 --> narrativeTelemetry_70dfa1c5_result["result"]
  otelReceiver_bd752dec["otelReceiver"]
  UserRequest --> otelReceiver_bd752dec
  otelReceiver_bd752dec --> otelReceiver_bd752dec_result["result"]
  ingestConfig_c7e6037b["ingestConfig"]
  UserRequest --> ingestConfig_c7e6037b
  ingestConfig_c7e6037b --> ingestConfig_c7e6037b_result["result"]
  traceTypes_f94d53f8["traceTypes"]
  UserRequest --> traceTypes_f94d53f8
  traceTypes_f94d53f8 --> traceTypes_f94d53f8_result["result"]
  traceScan_d94d6b75["traceScan"]
  UserRequest --> traceScan_d94d6b75
  traceScan_d94d6b75 --> traceScan_d94d6b75_result["result"]
  traceScan_d94d6b75 --> traceParser_f261b9c1
  traceScan_d94d6b75 --> traceIngest_a4da94ac
  traceParser_f261b9c1["traceParser"]
  UserRequest --> traceParser_f261b9c1
  traceParser_f261b9c1 --> traceParser_f261b9c1_result["result"]
  traceIngest_a4da94ac["traceIngest"]
  UserRequest --> traceIngest_a4da94ac
  traceIngest_a4da94ac --> traceIngest_a4da94ac_result["result"]
  traceIngest_a4da94ac --> db_7bdc25d1
  traceIngest_a4da94ac --> traceParser_f261b9c1
  traceIngest_a4da94ac --> otelAdapter_570cff77
  traceConfig_7e9b1320["traceConfig"]
  UserRequest --> traceConfig_7e9b1320
  traceConfig_7e9b1320 --> traceConfig_7e9b1320_result["result"]
  testRuns_ebc7ce74["testRuns"]
  UserRequest --> testRuns_ebc7ce74
  testRuns_ebc7ce74 --> testRuns_ebc7ce74_result["result"]
  testRuns_ebc7ce74 --> db_7bdc25d1
  snapshots_2b36a6e6["snapshots"]
  UserRequest --> snapshots_2b36a6e6
  snapshots_2b36a6e6 --> snapshots_2b36a6e6_result["result"]
  snapshots_2b36a6e6 --> git_9a881b9b
  shell_ce635c4e["shell"]
  UserRequest --> shell_ce635c4e
  shell_ce635c4e --> shell_ce635c4e_result["result"]
  sessions_1225ae6c["sessions"]
  UserRequest --> sessions_1225ae6c
  sessions_1225ae6c --> sessions_1225ae6c_result["result"]
  sessionLinking_8e056ceb["sessionLinking"]
  UserRequest --> sessionLinking_8e056ceb
  sessionLinking_8e056ceb --> sessionLinking_8e056ceb_result["result"]
  sessionBadges_4a38460b["sessionBadges"]
  UserRequest --> sessionBadges_4a38460b
  sessionBadges_4a38460b --> sessionBadges_4a38460b_result["result"]
  sessionBadges_4a38460b --> sessions_1225ae6c
  sessionBadges_4a38460b --> sessionLinking_8e056ceb
  otelAdapter_570cff77["otelAdapter"]
  UserRequest --> otelAdapter_570cff77
  otelAdapter_570cff77 --> otelAdapter_570cff77_result["result"]
  otelAdapter_570cff77 --> git_9a881b9b
  narrativeFeedback_16021c8c["narrativeFeedback"]
  UserRequest --> narrativeFeedback_16021c8c
  narrativeFeedback_16021c8c --> narrativeFeedback_16021c8c_result["result"]
  narrativeFeedback_16021c8c --> db_7bdc25d1
  meta_ea3bd73e["meta"]
  UserRequest --> meta_ea3bd73e
  meta_ea3bd73e --> meta_ea3bd73e_result["result"]
  kimiAdapter_baf31ed8["kimiAdapter"]
  UserRequest --> kimiAdapter_baf31ed8
  kimiAdapter_baf31ed8 --> kimiAdapter_baf31ed8_result["result"]
  junit_018bb207["junit"]
  UserRequest --> junit_018bb207
  junit_018bb207 --> junit_018bb207_result["result"]
  indexer_70fa78e5["indexer"]
  UserRequest --> indexer_70fa78e5
  indexer_70fa78e5 --> indexer_70fa78e5_result["result"]
  indexer_70fa78e5 --> composeBranchNarrative_2a286eb3
  indexer_70fa78e5 --> db_7bdc25d1
  indexer_70fa78e5 --> sessions_1225ae6c
  indexer_70fa78e5 --> agentTrace_bc847946
  indexer_70fa78e5 --> traceConfig_7e9b1320
  indexer_70fa78e5 --> story_anchors_api_279f63a1
  indexer_70fa78e5 --> testRuns_ebc7ce74
  indexer_70fa78e5 --> snapshots_2b36a6e6
  githubContext_f8e56c92["githubContext"]
  UserRequest --> githubContext_f8e56c92
  githubContext_f8e56c92 --> githubContext_f8e56c92_result["result"]
  gitNotes_8e1bf058["gitNotes"]
  UserRequest --> gitNotes_8e1bf058
  gitNotes_8e1bf058 --> gitNotes_8e1bf058_result["result"]
  gitNotes_8e1bf058 --> git_9a881b9b
  git_9a881b9b["git"]
  UserRequest --> git_9a881b9b
  git_9a881b9b --> git_9a881b9b_result["result"]
  git_9a881b9b --> shell_ce635c4e
  db_7bdc25d1["db"]
  UserRequest --> db_7bdc25d1
  db_7bdc25d1 --> db_7bdc25d1_result["result"]
  codexConfig_229b7351["codexConfig"]
  UserRequest --> codexConfig_229b7351
  codexConfig_229b7351 --> codexConfig_229b7351_result["result"]
  agentTrace_bc847946["agentTrace"]
  UserRequest --> agentTrace_bc847946
  agentTrace_bc847946 --> agentTrace_bc847946_result["result"]
  agentTrace_bc847946 --> db_7bdc25d1
  agentTrace_bc847946 --> otelAdapter_570cff77
  agentSessionTools_413c0d20["agentSessionTools"]
  UserRequest --> agentSessionTools_413c0d20
  agentSessionTools_413c0d20 --> agentSessionTools_413c0d20_result["result"]
  composeBranchNarrative_2a286eb3["composeBranchNarrative"]
  UserRequest --> composeBranchNarrative_2a286eb3
  composeBranchNarrative_2a286eb3 --> composeBranchNarrative_2a286eb3_result["result"]
  classDef dbNode fill:#0ea5e9,color:#fff
  classDef decisionNode fill:#0284c7,color:#fff