flowchart TD
  Start(["Start"])
  vite_integration_config_033b7d32["vite.integration.config"]
  Start --> vite_integration_config_033b7d32
  vite_config_c473fba0["vite.config"]
  vite_integration_config_033b7d32 --> vite_config_c473fba0
  test_debug_e2f6f6a5["test-debug"]
  vite_config_c473fba0 --> test_debug_e2f6f6a5
  playwright_config_c5f93a12["playwright.config"]
  test_debug_e2f6f6a5 --> playwright_config_c5f93a12
  setupTests_a1881263["setupTests"]
  playwright_config_c5f93a12 --> setupTests_a1881263
  axe_config_5dab6a88["axe-config"]
  setupTests_a1881263 --> axe_config_5dab6a88
  vite_config_1_736b3c02["vite.config"]
  axe_config_5dab6a88 --> vite_config_1_736b3c02
  trace_visual_system_v1_spec_98815fb6["trace-visual-system-v1.spec"]
  vite_config_1_736b3c02 --> trace_visual_system_v1_spec_98815fb6
  End(["End"])
  trace_visual_system_v1_spec_98815fb6 --> End