flowchart TD
  Start(["Start"])
  vite_integration_config_033b7d32["vite.integration.config"]
  Start --> vite_integration_config_033b7d32
  vite_config_c473fba0["vite.config"]
  vite_integration_config_033b7d32 --> vite_config_c473fba0
  playwright_config_c5f93a12["playwright.config"]
  vite_config_c473fba0 --> playwright_config_c5f93a12
  setupTests_a1881263["setupTests"]
  playwright_config_c5f93a12 --> setupTests_a1881263
  axe_config_5dab6a88["axe-config"]
  setupTests_a1881263 --> axe_config_5dab6a88
  firefly_visual_system_v1_spec_def11f59["firefly-visual-system-v1.spec"]
  axe_config_5dab6a88 --> firefly_visual_system_v1_spec_def11f59
  critical_flows_spec_66db3f9a["critical-flows.spec"]
  firefly_visual_system_v1_spec_def11f59 --> critical_flows_spec_66db3f9a
  app_spec_fe94aeca["app.spec"]
  critical_flows_spec_66db3f9a --> app_spec_fe94aeca
  End(["End"])
  app_spec_fe94aeca --> End