flowchart LR
  User(("User"))
  useTraceCollector_e3f811c3["useTraceCollector"]
  User --> useTraceCollector_e3f811c3
  useSourceLensData_c1b2d5d3["useSourceLensData"]
  User --> useSourceLensData_c1b2d5d3
  useAutoIngest_56f90d17["useAutoIngest"]
  User --> useAutoIngest_56f90d17
  story_anchors_api_279f63a1["story-anchors-api"]
  User --> story_anchors_api_279f63a1
  rules_6c621d1a["rules"]
  User --> rules_6c621d1a
  attribution_api_b53df9d9["attribution-api"]
  User --> attribution_api_b53df9d9
  atlas_api_0fe43c81["atlas-api"]
  User --> atlas_api_0fe43c81
  docsAutoLoad_44c379b9["docsAutoLoad"]
  User --> docsAutoLoad_44c379b9
  branchViewEvidence_9e7c8d82["branchViewEvidence"]
  User --> branchViewEvidence_9e7c8d82
  branchView_types_1fc9620a["branchView.types"]
  User --> branchView_types_1fc9620a
  branchView_constants_91490435["branchView.constants"]
  User --> branchView_constants_91490435
  branchHeaderMapper_4dd9295b["branchHeaderMapper"]
  User --> branchHeaderMapper_4dd9295b
  useTraceCollector_test_1261d5ea["useTraceCollector.test"]
  User --> useTraceCollector_test_1261d5ea
  useSourceLensData_test_7459bf0f["useSourceLensData.test"]
  User --> useSourceLensData_test_7459bf0f
  useAutoIngest_test_c64ef81e["useAutoIngest.test"]
  User --> useAutoIngest_test_c64ef81e
  otelReceiver_bd752dec["otelReceiver"]
  User --> otelReceiver_bd752dec
  narrativeFs_b94b096d["narrativeFs"]
  User --> narrativeFs_b94b096d
  ingestConfig_c7e6037b["ingestConfig"]
  User --> ingestConfig_c7e6037b
  gitDiff_a3685ce7["gitDiff"]
  User --> gitDiff_a3685ce7
  activity_0651863b["activity"]
  User --> activity_0651863b
  traceScan_d94d6b75["traceScan"]
  User --> traceScan_d94d6b75
  sessions_1225ae6c["sessions"]
  User --> sessions_1225ae6c
  sessionLinking_8e056ceb["sessionLinking"]
  User --> sessionLinking_8e056ceb
  codexConfig_229b7351["codexConfig"]
  User --> codexConfig_229b7351
  agentTrace_bc847946["agentTrace"]
  User --> agentTrace_bc847946
  agentSessionTools_413c0d20["agentSessionTools"]
  User --> agentSessionTools_413c0d20
  attribution_api_test_e7248f37["attribution-api.test"]
  User --> attribution_api_test_e7248f37
  useBranchViewController_d4c2a4b8["useBranchViewController"]
  User --> useBranchViewController_d4c2a4b8
  useBranchSelectionData_213a448c["useBranchSelectionData"]
  User --> useBranchSelectionData_213a448c
  docsAutoLoad_test_e6636ba5["docsAutoLoad.test"]
  User --> docsAutoLoad_test_e6636ba5
  branchViewEvidence_test_c375af04["branchViewEvidence.test"]
  User --> branchViewEvidence_test_c375af04
  BranchView_test_9e320760["BranchView.test"]
  User --> BranchView_test_9e320760
  sessionExcerpts_utils_07a2d1bb["sessionExcerpts.utils"]
  User --> sessionExcerpts_utils_07a2d1bb
  types_1_4ecdf56e["types"]
  User --> types_1_4ecdf56e
  timeRangeUtils_e17b2759["timeRangeUtils"]
  User --> timeRangeUtils_e17b2759
  branchHeaderMapper_test_8c33a8eb["branchHeaderMapper.test"]
  User --> branchHeaderMapper_test_8c33a8eb
  codexAppServerContractParity_test_dfc03ace["codexAppServerContractParity.test"]
  User --> codexAppServerContractParity_test_dfc03ace
  agentTraceNormalization_test_f7097cf9["agentTraceNormalization.test"]
  User --> agentTraceNormalization_test_f7097cf9
  main_0d6e4079["main"]
  User --> main_0d6e4079
  App_0d04bfeb["App"]
  User --> App_0d04bfeb
  DocsView_37d8072c["DocsView"]
  User --> DocsView_37d8072c
  DashboardView_16aa3601["DashboardView"]
  User --> DashboardView_16aa3601
  BranchViewLayout_2f34f6b8["BranchViewLayout"]
  User --> BranchViewLayout_2f34f6b8
  BranchView_16f1e1f8["BranchView"]
  User --> BranchView_16f1e1f8
  UpdatePrompt_8bfa5fb8["UpdatePrompt"]
  User --> UpdatePrompt_8bfa5fb8
  TraceTranscriptPanel_d443bb3b["TraceTranscriptPanel"]
  User --> TraceTranscriptPanel_d443bb3b
  TopNav_8615cc91["TopNav"]
  User --> TopNav_8615cc91
  Toggle_3d03a1de["Toggle"]
  User --> Toggle_3d03a1de
  TimelineNode_8b6735fa["TimelineNode"]
  User --> TimelineNode_8b6735fa
  TimelineNavButtons_cf793ac5["TimelineNavButtons"]
  User --> TimelineNavButtons_cf793ac5
  Timeline_9dcff98e["Timeline"]
  User --> Timeline_9dcff98e
  TestResultsPanel_e82e112c["TestResultsPanel"]
  User --> TestResultsPanel_e82e112c
  TelemetrySettingsPanel_092f60ae["TelemetrySettingsPanel"]
  User --> TelemetrySettingsPanel_092f60ae
  StoryAnchorsPanel_dd7a121f["StoryAnchorsPanel"]
  User --> StoryAnchorsPanel_dd7a121f
  StepsSummaryCard_9d9d3d07["StepsSummaryCard"]
  User --> StepsSummaryCard_9d9d3d07
  SourceLensView_034e671f["SourceLensView"]
  User --> SourceLensView_034e671f
  SourceLensStats_a046f588["SourceLensStats"]
  User --> SourceLensStats_a046f588
  SourceLensLineTable_35653c59["SourceLensLineTable"]
  User --> SourceLensLineTable_35653c59
  SourceLensEmptyStates_0d01a55e["SourceLensEmptyStates"]
  User --> SourceLensEmptyStates_0d01a55e
  Skeleton_ea5f6bdc["Skeleton"]
  User --> Skeleton_ea5f6bdc
  SessionImportPanel_44d8f995["SessionImportPanel"]
  User --> SessionImportPanel_44d8f995
  SessionExcerpts_30b0b8dc["SessionExcerpts"]
  User --> SessionExcerpts_30b0b8dc
  Select_2a78025d["Select"]
  User --> Select_2a78025d
  RightPanelTabs_29002826["RightPanelTabs"]
  User --> RightPanelTabs_29002826
  RepositoryPlaceholderCard_2ded572d["RepositoryPlaceholderCard"]
  User --> RepositoryPlaceholderCard_2ded572d
  RepoEmptyState_40528d79["RepoEmptyState"]
  User --> RepoEmptyState_40528d79
  NeedsAttentionList_62f25e04["NeedsAttentionList"]
  User --> NeedsAttentionList_62f25e04
  NarrativeGovernancePanel_18468a63["NarrativeGovernancePanel"]
  User --> NarrativeGovernancePanel_18468a63
  MermaidDiagram_5d578741["MermaidDiagram"]
  User --> MermaidDiagram_5d578741
  IntentList_2ae18a16["IntentList"]
  User --> IntentList_2ae18a16
  IngestToast_ef341876["IngestToast"]
  User --> IngestToast_ef341876
  IngestStatusStrip_11dfe0c2["IngestStatusStrip"]
  User --> IngestStatusStrip_11dfe0c2
  ImportErrorBanner_d00028a3["ImportErrorBanner"]
  User --> ImportErrorBanner_d00028a3
  HelpPopover_954f9250["HelpPopover"]
  User --> HelpPopover_954f9250
  GitHubConnectorPanel_f94f3952["GitHubConnectorPanel"]
  User --> GitHubConnectorPanel_f94f3952
  FireflySignal_b76b6c4c["FireflySignal"]
  User --> FireflySignal_b76b6c4c
  FireflyHero_stories_80e010e9["FireflyHero.stories"]
  User --> FireflyHero_stories_80e010e9
  Firefly_c924d48a["Firefly"]
  User --> Firefly_c924d48a
  FilesChanged_eb0b117d["FilesChanged"]
  User --> FilesChanged_eb0b117d
  DocsOverviewPanel_161198dc["DocsOverviewPanel"]
  User --> DocsOverviewPanel_161198dc
  DiffViewer_7e36d3d0["DiffViewer"]
  User --> DiffViewer_7e36d3d0
  Dialog_69b51517["Dialog"]
  User --> Dialog_69b51517
  DecisionArchaeologyPanel_bd32c4aa["DecisionArchaeologyPanel"]
  User --> DecisionArchaeologyPanel_bd32c4aa
  Checkbox_d103a138["Checkbox"]
  User --> Checkbox_d103a138
  CaptureActivityStrip_ca040f21["CaptureActivityStrip"]
  User --> CaptureActivityStrip_ca040f21
  Breadcrumb_2bd873d6["Breadcrumb"]
  User --> Breadcrumb_2bd873d6
  BranchSummaryBar_843c8e56["BranchSummaryBar"]
  User --> BranchSummaryBar_843c8e56
  BranchNarrativePanel_c0952487["BranchNarrativePanel"]
  User --> BranchNarrativePanel_c0952487
  BranchHeader_d067325d["BranchHeader"]
  User --> BranchHeader_d067325d
  BadgePill_b0287413["BadgePill"]
  User --> BadgePill_b0287413
  AutoIngestSetupPanel_4e463af3["AutoIngestSetupPanel"]
  User --> AutoIngestSetupPanel_4e463af3
  AuthorBadge_9ac9f202["AuthorBadge"]
  User --> AuthorBadge_9ac9f202
  AttributionSettingsPanel_7cbc28fe["AttributionSettingsPanel"]
  User --> AttributionSettingsPanel_7cbc28fe
  AtlasSearchPanel_3daa12fa["AtlasSearchPanel"]
  User --> AtlasSearchPanel_3daa12fa
  AiContributionBadge_a0737f87["AiContributionBadge"]
  User --> AiContributionBadge_a0737f87
  AgentTraceSummary_3b3c264c["AgentTraceSummary"]
  User --> AgentTraceSummary_3b3c264c
  DashboardView_test_bc2935bd["DashboardView.test"]
  User --> DashboardView_test_bc2935bd
  BranchView_test_1_123b1973["BranchView.test"]
  User --> BranchView_test_1_123b1973
  StoryAnchorsSections_793c218e["StoryAnchorsSections"]
  User --> StoryAnchorsSections_793c218e
  SessionExcerptsParts_f3184ff0["SessionExcerptsParts"]
  User --> SessionExcerptsParts_f3184ff0
  RightPanelTabPanels_82d72294["RightPanelTabPanels"]
  User --> RightPanelTabPanels_82d72294
  RightPanelTabBar_431349ca["RightPanelTabBar"]
  User --> RightPanelTabBar_431349ca
  DiffDock_195b6999["DiffDock"]
  User --> DiffDock_195b6999
  AppearanceCard_05dda86e["AppearanceCard"]
  User --> AppearanceCard_05dda86e
  TopFilesTable_aaff44a1["TopFilesTable"]
  User --> TopFilesTable_aaff44a1
  MetricsGrid_4b46425d["MetricsGrid"]
  User --> MetricsGrid_4b46425d
  MetricCard_0f9b6c6e["MetricCard"]
  User --> MetricCard_0f9b6c6e
  DashboardLoadingState_dca2319d["DashboardLoadingState"]
  User --> DashboardLoadingState_dca2319d
  DashboardHeader_a24e8484["DashboardHeader"]
  User --> DashboardHeader_a24e8484
  DashboardErrorState_eb2effe9["DashboardErrorState"]
  User --> DashboardErrorState_eb2effe9
  DashboardEmptyState_2c6487fe["DashboardEmptyState"]
  User --> DashboardEmptyState_2c6487fe
  TelemetrySettingsPanel_test_50d8c8a4["TelemetrySettingsPanel.test"]
  User --> TelemetrySettingsPanel_test_50d8c8a4
  StoryAnchorsPanel_test_e6427ced["StoryAnchorsPanel.test"]
  User --> StoryAnchorsPanel_test_e6427ced
  SessionImportPanel_test_2f6412b2["SessionImportPanel.test"]
  User --> SessionImportPanel_test_2f6412b2
  RightPanelTabs_test_bf4d2cd2["RightPanelTabs.test"]
  User --> RightPanelTabs_test_bf4d2cd2
  FireflySignal_test_3aabe6b2["FireflySignal.test"]
  User --> FireflySignal_test_3aabe6b2
  DocsOverviewPanel_test_41f82ab6["DocsOverviewPanel.test"]
  User --> DocsOverviewPanel_test_41f82ab6
  CaptureActivityStrip_test_4f2b3391["CaptureActivityStrip.test"]
  User --> CaptureActivityStrip_test_4f2b3391
  useTraceCollector_e3f811c3 --> otelReceiver_bd752dec
  useTraceCollector_e3f811c3 --> traceConfig_7e9b1320
  useTraceCollector_e3f811c3 --> sessionLinking_8e056ceb
  useAutoIngest_56f90d17 --> otelReceiver_bd752dec
  useAutoIngest_56f90d17 --> activity_0651863b
  useTraceCollector_test_1261d5ea --> useTraceCollector_e3f811c3
  useSourceLensData_test_7459bf0f --> useSourceLensData_c1b2d5d3
  useAutoIngest_test_c64ef81e --> useAutoIngest_56f90d17
  traceScan_d94d6b75 --> narrativeFs_b94b096d
  sessions_1225ae6c --> narrativeFs_b94b096d
  codexConfig_229b7351 --> narrativeFs_b94b096d
  agentTrace_bc847946 --> narrativeFs_b94b096d
  agentTrace_bc847946 --> gitDiff_a3685ce7
  useBranchViewController_d4c2a4b8 --> branchView_constants_91490435
  useBranchViewController_d4c2a4b8 --> branchViewEvidence_9e7c8d82
  useBranchViewController_d4c2a4b8 --> useBranchSelectionData_213a448c
  branchViewEvidence_test_c375af04 --> branchViewEvidence_9e7c8d82
  BranchView_test_9e320760 --> branchViewEvidence_9e7c8d82
  agentTraceNormalization_test_f7097cf9 --> agentTrace_bc847946
  main_0d6e4079 --> App_0d04bfeb
  App_0d04bfeb --> otelReceiver_bd752dec
  App_0d04bfeb --> useAutoIngest_56f90d17
  App_0d04bfeb --> useTraceCollector_e3f811c3
  App_0d04bfeb --> RepoEmptyState_40528d79
  App_0d04bfeb --> TopNav_8615cc91
  App_0d04bfeb --> UpdatePrompt_8bfa5fb8
  App_0d04bfeb --> BranchView_16f1e1f8
  App_0d04bfeb --> DashboardView_16aa3601
  App_0d04bfeb --> DocsView_37d8072c
  DocsView_37d8072c --> DocsOverviewPanel_161198dc
  DashboardView_16aa3601 --> DashboardEmptyState_2c6487fe
  DashboardView_16aa3601 --> DashboardErrorState_eb2effe9
  DashboardView_16aa3601 --> DashboardHeader_a24e8484
  DashboardView_16aa3601 --> DashboardLoadingState_dca2319d
  DashboardView_16aa3601 --> MetricsGrid_4b46425d
  DashboardView_16aa3601 --> TopFilesTable_aaff44a1
  BranchViewLayout_2f34f6b8 --> BranchNarrativePanel_c0952487
  BranchViewLayout_2f34f6b8 --> BranchHeader_d067325d
  BranchViewLayout_2f34f6b8 --> BranchSummaryBar_843c8e56
  BranchViewLayout_2f34f6b8 --> Breadcrumb_2bd873d6
  BranchViewLayout_2f34f6b8 --> CaptureActivityStrip_ca040f21
  BranchViewLayout_2f34f6b8 --> DecisionArchaeologyPanel_bd32c4aa
  BranchViewLayout_2f34f6b8 --> FilesChanged_eb0b117d
  BranchViewLayout_2f34f6b8 --> ImportErrorBanner_d00028a3
  BranchViewLayout_2f34f6b8 --> IngestToast_ef341876
  BranchViewLayout_2f34f6b8 --> IntentList_2ae18a16
  BranchViewLayout_2f34f6b8 --> NarrativeGovernancePanel_18468a63
  BranchViewLayout_2f34f6b8 --> NeedsAttentionList_62f25e04
  BranchViewLayout_2f34f6b8 --> RightPanelTabs_29002826
  BranchViewLayout_2f34f6b8 --> Skeleton_ea5f6bdc
  BranchViewLayout_2f34f6b8 --> Timeline_9dcff98e
  BranchViewLayout_2f34f6b8 --> branchView_constants_91490435
  BranchView_16f1e1f8 --> BranchViewLayout_2f34f6b8
  BranchView_16f1e1f8 --> useBranchViewController_d4c2a4b8
  TimelineNode_8b6735fa --> BadgePill_b0287413
  Timeline_9dcff98e --> BadgePill_b0287413
  Timeline_9dcff98e --> FireflySignal_b76b6c4c
  Timeline_9dcff98e --> TimelineNavButtons_cf793ac5
  Timeline_9dcff98e --> TimelineNode_8b6735fa
  TelemetrySettingsPanel_092f60ae --> HelpPopover_954f9250
  TelemetrySettingsPanel_092f60ae --> Toggle_3d03a1de
  StepsSummaryCard_9d9d3d07 --> activity_0651863b
  SourceLensView_034e671f --> SourceLensEmptyStates_0d01a55e
  SourceLensView_034e671f --> SourceLensLineTable_35653c59
  SourceLensView_034e671f --> SourceLensStats_a046f588
  SourceLensView_034e671f --> useSourceLensData_c1b2d5d3
  SourceLensView_034e671f --> story_anchors_api_279f63a1
  SourceLensStats_a046f588 --> attribution_api_b53df9d9
  SourceLensLineTable_35653c59 --> attribution_api_b53df9d9
  SourceLensLineTable_35653c59 --> AuthorBadge_9ac9f202
  SessionImportPanel_44d8f995 --> Checkbox_d103a138
  SessionExcerpts_30b0b8dc --> sessionExcerpts_utils_07a2d1bb
  RightPanelTabs_29002826 --> DiffDock_195b6999
  RightPanelTabs_29002826 --> RightPanelTabBar_431349ca
  RightPanelTabs_29002826 --> RightPanelTabPanels_82d72294
  RepoEmptyState_40528d79 --> RepositoryPlaceholderCard_2ded572d
  IngestStatusStrip_11dfe0c2 --> Checkbox_d103a138
  GitHubConnectorPanel_f94f3952 --> Toggle_3d03a1de
  DocsOverviewPanel_161198dc --> MermaidDiagram_5d578741
  DocsOverviewPanel_161198dc --> RepositoryPlaceholderCard_2ded572d
  CaptureActivityStrip_ca040f21 --> Toggle_3d03a1de
  BadgePill_b0287413 --> AiContributionBadge_a0737f87
  AuthorBadge_9ac9f202 --> attribution_api_b53df9d9
  AttributionSettingsPanel_7cbc28fe --> HelpPopover_954f9250
  AttributionSettingsPanel_7cbc28fe --> Toggle_3d03a1de
  AgentTraceSummary_3b3c264c --> attribution_api_b53df9d9
  DashboardView_test_bc2935bd --> DashboardView_16aa3601
  BranchView_test_1_123b1973 --> BranchView_16f1e1f8
  SessionExcerptsParts_f3184ff0 --> Dialog_69b51517
  SessionExcerptsParts_f3184ff0 --> sessionExcerpts_utils_07a2d1bb
  RightPanelTabPanels_82d72294 --> AgentTraceSummary_3b3c264c
  RightPanelTabPanels_82d72294 --> AtlasSearchPanel_3daa12fa
  RightPanelTabPanels_82d72294 --> AttributionSettingsPanel_7cbc28fe
  RightPanelTabPanels_82d72294 --> AutoIngestSetupPanel_4e463af3
  RightPanelTabPanels_82d72294 --> GitHubConnectorPanel_f94f3952
  RightPanelTabPanels_82d72294 --> SessionExcerpts_30b0b8dc
  RightPanelTabPanels_82d72294 --> SourceLensView_034e671f
  RightPanelTabPanels_82d72294 --> StepsSummaryCard_9d9d3d07
  RightPanelTabPanels_82d72294 --> StoryAnchorsPanel_dd7a121f
  RightPanelTabPanels_82d72294 --> TelemetrySettingsPanel_092f60ae
  RightPanelTabPanels_82d72294 --> TestResultsPanel_e82e112c
  RightPanelTabPanels_82d72294 --> TraceTranscriptPanel_d443bb3b
  RightPanelTabPanels_82d72294 --> AppearanceCard_05dda86e
  RightPanelTabBar_431349ca --> types_1_4ecdf56e
  DiffDock_195b6999 --> DiffViewer_7e36d3d0
  AppearanceCard_05dda86e --> Toggle_3d03a1de
  MetricsGrid_4b46425d --> attribution_api_b53df9d9
  MetricsGrid_4b46425d --> MetricCard_0f9b6c6e
  DashboardHeader_a24e8484 --> timeRangeUtils_e17b2759
  DashboardEmptyState_2c6487fe --> RepositoryPlaceholderCard_2ded572d
  TelemetrySettingsPanel_test_50d8c8a4 --> TelemetrySettingsPanel_092f60ae
  StoryAnchorsPanel_test_e6427ced --> StoryAnchorsPanel_dd7a121f
  SessionImportPanel_test_2f6412b2 --> SessionImportPanel_44d8f995
  RightPanelTabs_test_bf4d2cd2 --> RightPanelTabs_29002826
  FireflySignal_test_3aabe6b2 --> FireflySignal_b76b6c4c
  DocsOverviewPanel_test_41f82ab6 --> DocsOverviewPanel_161198dc
  CaptureActivityStrip_test_4f2b3391 --> CaptureActivityStrip_ca040f21
  traceConfig_7e9b1320 --> narrativeFs_b94b096d
  classDef userNode fill:#16a34a,color:#fff