#!/usr/bin/env bash
# Refresh diagram context for trace-narrative
# Usage: scripts/refresh-diagram-context.sh [--dry-run|--force]

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DIAGRAM_DIR="$REPO_ROOT/.diagram"
CONTEXT_DIR="$DIAGRAM_DIR/context"
DRY_RUN="false"
FORCE="false"

# Parse args
for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN="true" ;;
    --force) FORCE="true" ;;
  esac
done

echo "== Diagram context refresh =="
echo "Repo root: $REPO_ROOT"
echo "Dry run: $DRY_RUN"
echo "Force: $FORCE"

# Ensure directories exist
mkdir -p "$DIAGRAM_DIR" "$CONTEXT_DIR"

# Check for diagram CLI
if ! command -v diagram &>/dev/null; then
  echo "[SKIP] diagram CLI not found. Install with: mise install @brainwav/diagram"
  echo "[INFO] Generating Mermaid diagrams from templates only..."
  SKIP_DIAGRAM_CLI="true"
else
  SKIP_DIAGRAM_CLI="false"
fi

if [[ "$DRY_RUN" == "true" ]]; then
  echo "[DRY-RUN] Would generate diagrams to $DIAGRAM_DIR/"
  echo "[DRY-RUN] Would generate context to $CONTEXT_DIR/diagram-context.md"
  exit 0
fi

# Generate all diagram types
echo ""
echo "Generating architecture diagrams..."
if [[ "$SKIP_DIAGRAM_CLI" == "false" ]]; then
  diagram all "$REPO_ROOT" \
    --output-dir "$DIAGRAM_DIR" \
    --patterns "**/*.ts,**/*.tsx,**/*.rs" \
    --exclude "node_modules/**,.git/**,dist/**,target/**,vendor/**" \
    --max-files 200
else
  echo "[SKIP] Skipping diagram CLI generation (CLI not available)"
fi

# Convert any SVG outputs to Mermaid format if needed
# The diagram CLI outputs SVG; we also create .mmd versions for AI context
echo ""
echo "Generating Mermaid files..."

# Generate component diagram
cat > "$DIAGRAM_DIR/component-map.mmd" << 'MMD'
flowchart TB
  subgraph Frontend["Frontend (React + Tauri)"]
    UI["src/ui/"]
    Hooks["src/hooks/"]
    Core["src/core/"]
  end

  subgraph Backend["Backend (Tauri/Rust)"]
    Commands["src-tauri/src/commands.rs"]
    CodexServer["src-tauri/src/codex_app_server.rs"]
    OTLPReceiver["src-tauri/src/otlp_receiver.rs"]
    SecretStore["src-tauri/src/secret_store.rs"]
    DB["SQLite via tauri-plugin-sql"]
  end

  subgraph External["External"]
    CodexCLI["Codex CLI (sidecar)"]
    OTEL["OTEL Collector"]
  end

  UI --> Hooks
  Hooks --> Core
  Core --> Commands
  Commands --> CodexServer
  Commands --> DB
  CodexServer --> CodexCLI
  OTLPReceiver --> OTEL
MMD

# Generate data flow diagram
cat > "$DIAGRAM_DIR/data-flow.mmd" << 'MMD'
flowchart LR
  subgraph Ingest["Ingest Layer"]
    TraceIngest["traceIngest.ts"]
    FileWatcher["file_watcher.rs"]
  end

  subgraph Storage["Storage Layer"]
    SQLite[(SQLite DB)]
    GitNotes["gitNotes.ts"]
  end

  subgraph Query["Query Layer"]
    Sessions["sessions.ts"]
    Narrative["composeBranchNarrative.ts"]
  end

  subgraph UI["UI Layer"]
    BranchPanel["BranchNarrativePanel"]
    TelemetryPanel["TelemetrySettingsPanel"]
  end

  TraceIngest --> SQLite
  FileWatcher --> SQLite
  SQLite --> Sessions
  SQLite --> Narrative
  Sessions --> BranchPanel
  Narrative --> BranchPanel
  GitNotes --> Narrative
MMD

# Generate auth flow diagram
cat > "$DIAGRAM_DIR/auth-flow.mmd" << 'MMD'
sequenceDiagram
  participant App as Tauri App
  participant Sidecar as Codex Sidecar
  participant Server as Codex Server
  participant GitHub as GitHub OAuth

  App->>Sidecar: initialize
  Sidecar->>Server: stdio handshake
  Server-->>Sidecar: initialized
  Sidecar-->>App: ready

  App->>Sidecar: login
  Sidecar->>Server: auth request
  Server->>GitHub: OAuth flow
  GitHub-->>Server: auth code
  Server-->>Sidecar: auth token
  Sidecar-->>App: authenticated

  App->>Sidecar: live events subscribe
  loop Stream Events
    Server-->>Sidecar: event
    Sidecar-->>App: event
  end
MMD

# Generate context markdown
echo ""
echo "Generating diagram context..."
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
COMMIT_SHA=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")

cat > "$CONTEXT_DIR/diagram-context.md" << CTX
# Diagram Context Pack

> Auto-generated by refresh-diagram-context.sh
> Do not hand-edit. Regenerate from source.

## Metadata

| Property | Value |
|----------|-------|
| Generated | $TIMESTAMP |
| Commit | $COMMIT_SHA |
| Schema | 1.0.0 |

## Architecture Overview

This is a Tauri desktop application with:

- **Frontend**: React + TypeScript + Tailwind v4
- **Backend**: Rust via Tauri
- **Sidecar**: Codex CLI for agentic operations
- **Storage**: SQLite for local persistence, git notes for session linking

## Component Map

See [\`.diagram/component-map.mmd\`](.diagram/component-map.mmd)

Key layers:
1. **UI Layer** (\`src/ui/\`) - React components, presentational
2. **Hooks Layer** (\`src/hooks/\`) - State management, data fetching
3. **Core Layer** (\`src/core/\`) - Business logic, repo operations
4. **Tauri Layer** (\`src-tauri/src/\`) - Rust commands, sidecar management

## Data Flow

See [\`.diagram/data-flow.mmd\`](.diagram/data-flow.mmd)

Primary data flow:
1. Trace ingest parses session files
2. SQLite stores structured data
3. Narrative composer queries for branch view
4. UI renders with attribution and feedback

## Auth Flow

See [\`.diagram/auth-flow.mmd\`](.diagram/auth-flow.mmd)

Authentication via Codex sidecar:
1. App initializes sidecar via stdio
2. Sidecar bridges to Codex server
3. OAuth flow through GitHub
4. Live events stream back to app

## Risk Tiers

From \`harness.contract.json\`:

| Tier | Paths | Rationale |
|------|-------|-----------|
| HIGH | \`src/core/security/**\`, \`src/core/tauri/**\`, secret store, OTLP receiver | Auth, secrets, IPC |
| MEDIUM | \`src/core/repo/**\`, \`src/hooks/**\`, Rust backend | Business logic, data |
| LOW | \`src/ui/**\`, tests, styles | Presentational |

## File Patterns

- TypeScript: \`src/**/*.ts\`, \`src/**/*.tsx\`
- Rust: \`src-tauri/src/**/*.rs\`
- Config: \`*.json\`, \`*.toml\`, \`*.yaml\`

## Excludes

- \`node_modules/\`
- \`.git/\`
- \`dist/\`, \`target/\`
- \`vendor/\`
CTX

# Generate metadata JSON
cat > "$CONTEXT_DIR/diagram-context.meta.json" << META
{
  "schema_version": "1.0.0",
  "generated_at": "$TIMESTAMP",
  "commit_sha": "$COMMIT_SHA",
  "repo_root": "$REPO_ROOT",
  "diagram_files": [
    "component-map.mmd",
    "data-flow.mmd",
    "auth-flow.mmd"
  ],
  "context_file": "diagram-context.md",
  "tool_version": "diagram $(diagram --version 2>/dev/null || echo 'unknown')"
}
META

echo ""
echo "[OK] Diagram context refresh complete"
echo "  - Diagrams: $DIAGRAM_DIR/*.mmd"
echo "  - Context: $CONTEXT_DIR/diagram-context.md"
echo "  - Metadata: $CONTEXT_DIR/diagram-context.meta.json"
